[system]
name = "x86_64-linux"    #Variations: x86_64-linux, x86_64-darwin, aarch64-linux, aarch64-darwin
time_zone = "Asia/Seoul"
host_name = "nixos"
state_version = "24.05"  #NixOS Version
shell = "zsh"            #Before change this, you should add exact programs to ./home/modules/program/${shell} what you choosed shell like "fish". By default, "zsh" and "nu" are supported.
locale = "ko_KR.UTF-8"   # default: en_US.UTF-8

[user]
name = "YOUR_NAME"               #For user and home directory
full_name = "your_full_name"     #For git user name
email = "your.email@example.com" #For git user email

[programs]
vscode_path = ""    #Vscode_path for wsl such as "/mnt/c/Users/YOUR_NAME/AppData/Local/Programs/Microsoft VS Code/bin"
win32yank_path = "" # Change to such as "/mnt/c/Users/YOUR_NAME/scoop/apps/win32yank/0.1.1" after installing win32yank on windows somehow.

[ssh]
enabled = false                                         #Change to true to enable the ssh key copy feature.
private_key_path = "/mnt/c/Users/YOUR_NAME/.ssh/id_rsa" #Do not place the file in this project.

[nixos]
config_path = "/tmp/my-nixos-config" #Path to the original nixos config directory to copy it to user home. If you want to continue with your nixos settings from the user home, this key must be filled in.
bkp_conf_dir_name = "nixos"          #Directory name to change from my-nixos-config

[home]
#Set packages you want to install. You can find available packages at https://search.nixos.org/packages
#'wget' is already included internally.(Check out ./home/default.nix);
packages = ["bat", "curl", "ripgrep", "tree", "jq", "httpie", "htop", "fd", "tmux"]

#Set additional PATHs for user session.
sessionPath = [
  #"/mnt/g/Programs/Ollama",
  #"/mnt/g/Programs/foobar2000"
]

#Set environment variables for user session.
[home.sessionVariables]
#JAVA_HOME = "/usr/lib/jvm/default-java"

#Set aliases for user session.
[home.shellAliases]
#ports = "netstat -tunlp"
#meminfo = "free -m -l -t -h"
