[system]
name = "x86_64-linux"    #Variations: x86_64-linux, x86_64-darwin, aarch64-linux, aarch64-darwin
time_zone = "Asia/Seoul"
host_name = "nixos"
state_version = "24.05"  #NixOS Version
shell = "zsh"            #Before change this, you should add exact programs to ./home/modules/program/${shell} what you choosed shell like "fish". By default, "zsh" and "nu" are supported.

[user]
name = "your_name"               #For user and home directory
full_name = "your_full_name"     #For git user name
email = "your.email@example.com" #For git user email

[programs]
vscode_path = "/mnt/c/Users/your_name/AppData/Local/Programs/Microsoft VS Code/bin" #Vscode_path for wsl

[ssh]
enabled = false                                         #Change to true to enable the ssh key copy feature.
private_key_path = "/mnt/c/Users/your_name/.ssh/id_rsa" #Do not place the file in this project.

[nixos]
config_path = "/tmp/my-nixos-config"   #Path to the original nixos config directory to copy it to user home. If you want to continue with your nixos settings from the user home, this key must be filled in.
backup_config_directory_name = "nixos" #Directory name to change from my-nixos-config
