
whell = "wheel"

[user]
name = "darren"
email = "your.email@example.com"
full_name = "Darren Kim"

[system]
name = "x86_64-linux"     #variations: x86_64-linux, x86_64-darwin, aarch64-linux, aarch64-darwin
timezone = "Asia/Kolkata"
hostname = "nixos1"
stateVersion = "24.05"

[programs]
terminal = "alacritty"
#editor = "vim"
vscode_path = "/mnt/c/Users/USERNAME/AppData/Local/Programs/Microsoft VS Code/Code.exe"
github_token = "your-github-token"

[ssh]
keys = ["ssh-ed25519 AAAA... your@email.com"]
